# Generated by Django 5.1.6 on 2025-04-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('date', models.DateField()),
                ('messages', models.CharField(max_length=400)),
                ('doctor_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
