# Generated by Django 5.1.6 on 2025-04-14 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_emergency_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergency',
            old_name='messages',
            new_name='message',
        ),
    ]
