# Generated by Django 5.1.6 on 2025-03-13 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=20)),
                ('jod', models.DateField()),
                ('profile', models.ImageField(upload_to='doctor_profile')),
                ('password', models.CharField(max_length=50)),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('contact', models.IntegerField()),
                ('aadhar_no', models.IntegerField(verbose_name=12)),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('is_patient', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
