# Generated by Django 5.1.6 on 2025-03-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctor_last_login_doctor_previous_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='aadhar_no',
            field=models.IntegerField(),
        ),
    ]
