# Generated by Django 5.1.6 on 2025-03-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_patient_aadhar_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='previous_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
