# Generated by Django 5.1.6 on 2025-03-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_patient1'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient1',
            name='email',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
