# Generated by Django 5.1.6 on 2025-04-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_patient1_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient1',
            name='profile',
            field=models.ImageField(default=2, upload_to='patient_profile'),
            preserve_default=False,
        ),
    ]
