# Generated by Django 5.1.6 on 2025-04-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_patient1_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='contact',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
