# Generated by Django 5.1.6 on 2025-04-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_doctor_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient1',
            name='patient_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
