# Generated by Django 5.1.6 on 2025-04-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_patient1_patient_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
