# Generated by Django 5.1.6 on 2025-03-27 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_patient1_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('appoint_date', models.DateField()),
                ('date', models.DateField()),
                ('purpose', models.CharField(max_length=200)),
                ('is_approved', models.BooleanField(default=False)),
                ('note', models.CharField(max_length=100)),
                ('doctor_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor')),
            ],
        ),
    ]
