# Generated by Django 5.1.6 on 2025-03-27 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appoint',
            old_name='date',
            new_name='dob',
        ),
    ]
