# Generated by Django 5.1.6 on 2025-03-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_rename_date_appoint_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='doctor_department',
            field=models.CharField(max_length=200),
        ),
    ]
