# Generated by Django 5.1.6 on 2025-03-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_appoint_doctor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoint',
            name='doctor',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
