# Generated by Django 5.1.6 on 2025-04-08 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_appoint_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='contact',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
