# Generated by Django 5.1.6 on 2025-04-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('jod', models.DateField()),
                ('ward', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
