# Generated by Django 5.1.6 on 2025-04-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('treatment_details', models.CharField(max_length=400)),
                ('doctor_name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
