# Generated by Django 5.1.6 on 2025-04-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0002_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discharge_date',
            field=models.DateTimeField(),
        ),
    ]
