# Generated by Django 5.1.6 on 2025-04-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0003_alter_invoice_discharge_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='patient_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
