# Generated by Django 5.1.6 on 2025-04-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0004_invoice_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
