# Generated by Django 5.1.6 on 2025-04-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0005_alter_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discharge_date',
            field=models.DateField(),
        ),
    ]
