# Generated by Django 5.1.6 on 2025-04-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0006_alter_invoice_discharge_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discharge_date',
            field=models.DateTimeField(),
        ),
    ]
